on: push

jobs:
  send_notify:
    name: Send notify to feishu webhook
    runs-on: ubuntu-latest
    steps:
    - uses: foxundermoon/feishu-action@v2
      with:
        url: ${{ secrets.BOT_WEBHOOK }}
        msg_type: post
        content: |
          post:
            zh_cn:
              title: New push from ${{ github.event.pusher.name }} in ${{ github.event.repository.name }}/${{ github.ref_name }}
              content:
              - - tag: text
                  un_escape: true
                  text: 'Commits:&#xA;&#xA;'
                - tag: text
                  un_escape: true
                  text: '${{ toJSON(join(github.event.commits.*.message, '&#xA;')) }}'
