on: [push, pull_request]

jobs:
  send_notify:
    name: Send notify to feishu webhook
    runs-on: ubuntu-latest
    steps:
    - uses: foxundermoon/feishu-action@v2
      with:
        url: https://open.feishu.cn/open-apis/bot/v2/hook/5552d16d-a73d-4f26-93fa-3d402e821c6c
        msg_type: post
        content: |
          post:
            zh_cn:
              title: Github连接测试
              content:
              - - tag: text
                  un_escape: true
                  text: '第一行&nbsp;:'
                - tag: a
                  text: 超链接
                  href: http://www.feishu.cn
                - tag: at
                  user_id: ou_18eac85d35a26f989317ad4f02e8bbbb
              - - tag: text
                  text: '第二行 :'
                - tag: text
                  text: 文本测试
